version: '3.8'

services:
  # Serviço MySQL para armazenamento de dados do Zabbix
  mysql-server:
    image: mysql
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: YjA0OTYwZDBiN2EwNWFjMTRjZGU3Yjcy
    volumes:
      - './zabbix/mysql:/var/lib/mysql'  # Volume para persistência de dados do MySQL
    command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  # Serviço Java Gateway do Zabbix
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway
    restart: unless-stopped

  # Serviço Zabbix Server com backend MySQL
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: YjA0OTYwZDBiN2EwNWFjMTRjZGU3Yjcy
      ZBX_JAVAGATEWAY: zabbix-java-gateway
    ports:
      - '10051:10051'  # Porta padrão para comunicação com agentes Zabbix
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'  # Volume para scripts de alerta personalizados
    restart: unless-stopped
    depends_on:
      - mysql-server
      - zabbix-java-gateway

  # Serviço Web do Zabbix com backend MySQL
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: YjA0OTYwZDBiN2EwNWFjMTRjZGU3Yjcy
    ports:
      - '80:8080'  # Porta padrão para acesso ao Zabbix Web
    restart: unless-stopped
    depends_on:
      - mysql-server
      - zabbix-server-mysql

  # Serviço Zabbix Agent para monitoramento de hosts
  zabbix-agent:
    image: zabbix/zabbix-agent
    environment:
      ZBX_HOSTNAME: Zabbix server
      ZBX_SERVER_HOST: zabbix-server-mysql
    depends_on:
      - zabbix-server-mysql
    restart: unless-stopped

  # Serviço Grafana para visualização de dados
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'  # Porta padrão para acesso ao Grafana
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app  # Instalação do plugin Zabbix App
    restart: unless-stopped
